### ISSUE TITLE
Timelapse mode not functioning

### ISSUE THREAD

**Issue by ljjh20** [royerlab/widgets#31]

**Comment by ljjh20** [comment]
- Timelapse code in Bin's code not refactored to support external stop call. Timelpase is therefore not functioning and it only implemented to not crash. Currently calls a worker with a duplicated of the live mode function.

**Comment by ljjh20** [comment]
- Timelapse mode currently makes to calls to the status bar.

**Comment by AhmetCanSolak** [comment]
I will be refactoring timelapse code tomorrow to make it compatible with recent developments . On GUI you did a good job already @ljjh20 , after my refactor should be easy to connect it.

**Comment by AhmetCanSolak** [comment]
addressed the concerns on hardware api level on #35  and merged. you can connect the gui.

**Comment by ljjh20** [comment]
Connected
